#!/bin/bash

usage(){ echo "
#################################
#                               #
# Ussage:                       #
#    $> ./<script> <ip list>    #
#      Please use the absolute  #
# file path for the ip list.    #
#                               #
#################################
"
}

if [ $# -eq 0 ]; then #If the user runs the command it will display the usage statment
        usage
elif [ $# -eq 1 ]; then #If there  something listed after the script then it will try and read it
        iplist=$1
        while read hostip #reads file (iplist) line by line
        do
                echo -e "\nRunning dd test on $hostip"
                ssh -n root@$hostip 'count=1; while [[ $count -le 10 ]]; do (echo -e "\n Run $count   $(date)"; dd if=/dev/zero of=~/testfile bs=128k count=1000 oflag=direct; echo -e "\n" ) >>~/dd_test 2>&1; rm -f testfile; count=$(echo "$count+1" | bc ); done'
                  # SSH's into host, and runs a dd test command 10 times and writes it to a file called dd_test
        done < $iplist #Rinse wash repeat
fi
