#!/bin/bash

#Pushing file to hosts

check-list(){
while [[ ! -f $iplist ]]; do
        echo -e "\nFile $iplist doesn't exitst"
        echo -e "Pleas enter the list of IP(txt file): \c"
                read iplist
done
}

check-file(){
while [[ ! -f $copyfile ]]; do
        read -p "Please enter a vaild file path: " copyfile
done
}

if [ -z $1 ]; then

echo -e " ######################################################
#                                                      #
# This script will push a selected file the /etc/      #
# directory of specified host.                         #
#                                                      #
# Usage:                                               #
# Use this syntax if you have a list of IPs            #
# $> ./<script> <file with ip list> <file to copy>     #
#                                                      #
# or                                                   #
#                                                      #
# Use this syntax to run it one host at a time         #
# $> ./<script> #Use the interactive mode              #
#                                                      #
########################################################"

        read -p "Press any key to continue... "

        echo -e "\n(Please use the absolute path)\nEnter file to copy: \c"
                read copyfile
                check-file

        echo -e "\nPlease enter IP: \c"
                read singleip


elif [ $# -eq 1 ]; then
        copyfile=/etc/hosts
        iplist=$1
        check-list

else
        iplist=$1
        copyfile=$2
        check-list
fi

echo -e "\n$(date)" >> completed_host

if [ -z $singleip ]; then

        while read hostip
        do
                echo -e "\nMaking a backup of $hostip's hosts file "
                ssh -n root@$hostip "cp -p /etc/hosts /etc/hosts_bu"
                echo -e "Copying new file to $hostip /etc/"
                scp -p $copyfile root@$hostip:/etc/
                echo -e "Adding itself to the hostfile"
#               ssh -n root@$hostip "echo "$hostip /bin/hostname" >> /etc/hosts "
                ssh -n root@$hostip "echo -n "$hostip" >> /etc/hosts && /bin/hostname >> /etc/hosts && sed -i 's/"$hostip"/"$hostip"   /g' /etc/hosts"
                echo -e "$hostip's hosts file has been changed." >> completed_host

        done < $iplist
else
        echo "Try again"
        while true
         do
                echo -e "\nMaking a backup of $hostip's hosts file "
                ssh -n $singleip "cp -p /etc/hosts /etc/hosts_bu "
                echo -e "Copying new file to $hostip /etc/"
                scp -p $copyfile root@$singleip:/etc/
                echo -e "$singleip's hosts file has been changed." >> completed_host
                echo -e "Adding itself to the hostfile"
#               ssh -n root@$hostip "echo "$hostip /bin/hostname" >> /etc/hosts "
                ssh -n root@$singleip "echo -n "$singleip" >> /etc/hosts && /bin/hostname >> /etc/hosts && sed -i 's/"$singleip"/"$singleip"   /g' /etc/hosts"

                echo -e "\n(Absolute path please)\nEnter file to copy: \c"
                read copyfile

                echo -e "\nPlease enter IP: \c"
                read singleip

        done
fi
