#!/bin/bash

usage(){
echo -e "
        #############################################
        #                                           #
        #  Usage:                                   #
        #    This script will push out ssh keys     #
        #    for ESXi hosts                         #
        #                                           #
        #  To run the scipt:                        #
        #    $> ./<script> <iplist> <ssh-key>       #
        #     *The ssh-key is a txt file            #
        #      with the key in it                   #
        #     *Only one ssh key per line            #
        #     *iplist- single ip on each line       #
        #                                           #
        #############################################"
}

check(){
while [[ ! -f $iplist ]]
        do
        echo -e "Please enter path for iplist: \c"
        read iplist
        done
}

if [ $# -eq 2 ]; then
        iplist=$1
        ssh_key=$2
        check

        while read hostip
        do

        key=$(cat ssh_key)
        echo -e "\n$(tput setaf 2)Pushing file out to host: $hostip $(tput sgr0)"
        ssh -n root@$hostip "echo -e "$key" >> ~/etc/ssh/keys-root/authorized_keys" ";sed -i 's/ssh-rsa/\nssh-rsa /g' ~/etc/ssh/keys-root/authorized_keys "

        done < $iplist
else
        usage
fi
